google_app_id: '91792495969-osemcsaqe50e7id9hvkogjvrdf1li9uh.apps.googleusercontent.com'
google_app_secret: 'FZCZob_BFZlycJqHtsPeVYoZ'

line_pay_id: '1656233882'
line_pay_secret: '81e006aba803909a26ad2530be5ea00a'
